baseURL: "https://immutable-tag.github.io"
enableInlineShortcodes: true
languageCode: "en-us"
title: "Immutable Tag"
theme: "uwe-uwe"
relativeURLs: true

disableKinds:
    - "section"
    - "taxonomy"
    - "term"
    - "RSS"

params:

    uweuwe:
        metadata:
            author: "Vasudha Jha"

        logo: 
            display: false
            src: "/assets/img/uwe-uwe-logo.png"

        shortDesc: 
            display: true
            value: "Guaranteeing immutability of version control system tags using blockchain"

        platformLinks:
            display: true
            displayMode: "as-icons-and-text" # Possible values: as-text | as-icons | as-icons-and-text

            platforms:
                -   name: "github"
                    display: true
                    iconSrc: "/assets/img/icons-platforms/github-icon.svg"
                    target: "https://github.com/Immutable-Tag"
                    text: "GitHub"
                    title: "Go to Immutable Tag's Github organization"

        toc: 
            display: true

        renderHooks:
            image:
                use: true

            link:
                use: true

            heading:
                use: true

        syntaxHiglighingCustom:
            use: false

markup:
    goldmark:
        renderer:
            unsafe: true

    highlight:
        anchorLineNos: false
        codeFences: true
        guessSyntax: false
        hl_Lines: ""
        lineAnchors: ""
        lineNoStart: 1
        lineNos: false
        lineNumbersInTable: true
        noClasses: true
        style: igor
        tabWidth: 4